[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  VITE_API_URL = "https://cloudtab-backend.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200